Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,21 +25,20 @@ jobs:
         SDL_RELEASE_TAG=release-2.30.2
         SDL_SHARED_LIBRARY=libSDL2-2.0.so.0.3000.2
         if [ ! -f external/SDL/build/${SDL_SHARED_LIBRARY} ]; then
-          echo "Building the SDL library..."
-          cd external
-          rm -rf SDL
-          git clone https://github.com/libsdl-org/SDL.git
-          cd SDL
-          git checkout $SDL_RELEASE_TAG
-          mkdir build
-          cd build
-          cmake -DCMAKE_BUILD_TYPE=Release -S .. -B .
-          if [ $(grep PKG_PIPEWIRE_VERSION:INTERNAL= CMakeCache.txt) = "PKG_PIPEWIRE_VERSION:INTERNAL=" ]; then
-              echo "The SDL library is not configured with PipeWire support, aborting. Check this?"
-              exit 1
+         echo "Building the SDL library..."
+         cd external
+         rm -rf SDL
+         git clone https://github.com/libsdl-org/SDL.git
+         cd SDL
+         git checkout $SDL_RELEASE_TAG
+         mkdir build
+         cd build
+         cmake -DCMAKE_BUILD_TYPE=Release -S .. -B .
+         if [ $(grep PKG_PIPEWIRE_VERSION:INTERNAL= CMakeCache.txt) = "PKG_PIPEWIRE_VERSION:INTERNAL=" ]; then
+          echo "The SDL library is not configured with PipeWire support, aborting. Check this?"
+          exit 1
           fi
         make -j4
-           cd ../../..
         else
            echo "The SDL library has already been built, skipping this step"
         fi
